export * from './HeaderTitle'
export * from './InfoText'
export * from './Label'
export * from './PageHeading'
export * from './SectionHeading'
export * from './Smaller'
export * from './SectionHeadingText'