# This is a basic workflow to help you get started with Actions

name: Build Prod

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build for prod
        run: NODE_ENV=prod npm run build
        
      - name: Publish artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: build-folder
          path: ${{ github.workspace }}/build/
          if-no-files-found: error
          
  deploy-pages:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download build folder
        uses: actions/download-artifact@v2.0.9
        with:
          name: build-folder
          path: build
      - name: Deploy to GitHub Pages
        if: success()
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
